# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-21 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showmanager', '0002_auto_20171103_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
